name: Auto Publish Blog

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ ! -f requirements.txt ]; then
            echo "requirements.txt not found. Exiting."
            exit 1
          fi
          pip install -r requirements.txt

      - name: Load environment variables
        run: |
          if [ -f .env ]; then
            export $(cat .env | grep -v ^# | xargs)
          fi

      - name: Generate new blog topics
        run: python generate_topics.py

      - name: Generate blog article
        run: python generate_article.py

      - name: Post blog article
        run: python post_article.py

