name: Auto Blog Publisher

on:
  schedule:
    - cron: "0 */2 * * *"  # Every 2 hours
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Check for requirements.txt file
        run: |
          if [ ! -f requirements.txt ]; then
            echo "❌ requirements.txt not found. Exiting."
            exit 1
          fi

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate topics if needed
        run: python generate_topics.py

      - name: Generate article
        run: python generate_article.py

      - name: Post article
        run: python post_article.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: publish article" || echo "No changes to commit"
          git push

