name: Generate and Publish AI Blog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set HF_TOKEN environment variable
        run: echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> $GITHUB_ENV

      - name: Generate topics
        run: python generate_topics.py
        env:
          HF_API_KEY: ${{ secrets.HF_TOKEN }}  # Set HF_API_KEY from GitHub secrets

      - name: Generate article
        run: python generate_article.py

      - name: Post article
        run: python post_article.py
